version: '3'
services:
  web:
      stdin_open: true
      build:  #we need to specify Dockerfile with custom name
          context: . #specify path where we put Dockerfile
          dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - /app/node_modules #bookmark volumes (to avoid mapping and used that one in container)
        - .:/app #mapping between current local folder and  folder 'app' in container
  tests:
    # second container used only for tests (not interactive, only execute test but you cannot interact in shell)
    # an alternative could be to execute test attaching to the first container
    # docker exec -it <ID> npm run test
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - .:/app
      command: ["npm", "run", "test"] #override default container command specified in Dockerfile